name: flutter_gen_ai_chat_ui
description: "High-performance Flutter UI kit for AI chat: streaming markdown, code highlighting, theming, and customizable integration hooks for major LLMs."
version: 2.0.8
homepage: https://github.com/hooshyar/flutter_gen_ai_chat_ui
repository: https://github.com/hooshyar/flutter_gen_ai_chat_ui
issue_tracker: https://github.com/hooshyar/flutter_gen_ai_chat_ui/issues
documentation: https://github.com/hooshyar/flutter_gen_ai_chat_ui/blob/main/README.md
keywords:
  [
    flutter,
    flutter package,
    ai chat,
    chatbot,
    conversational ai,
    llm,
    chatgpt,
    gemini,
    claude,
    code highlighting,
    markdown,
    streaming text,
    customizable ui,
    performance,
    mobile sdk,
    pubdev,
  ]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  intl: ^0.19.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.1.0
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  flutter_streaming_text_markdown: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  speech_to_text: ^6.6.1
  network_image_mock: ^2.1.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Expose integration test files
  assets:
    - integration_test/
    - integration_test/utils/
